import type { Metadata } from 'next'
import { Geist_Mono, Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/components/providers'
import Footer from '@/components/ui/footer/footer'
import LayoutHeader from '@/components/ui/headers/layout-header'
import { Toaster } from 'sonner'

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: "Pat's Web Dev Tutoring ",
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} ${geistMono.variable} antialiased`}
			>
				<LayoutHeader />
				<Providers>{children}</Providers>
				 <Toaster />
				<Footer />
			</body>
		</html>
	)
}
